### ISSUE TITLE
Use publickey.js to search public keys

### ISSUE THREAD

**Issue by diafygi** [Gaff/pgp.help#24]
I'd like to request that you allow searching for public keys in SKS-keyserver pool and Keybase. It would be helpful to be able to find others just based on their email/twitter/github/etc.

https://github.com/diafygi/publickeyjs

**Comment by Gaff** [comment]
Hi,

Sorry I missed this comment, and thanks for the feedback.

I've considered this. The problem is it would break my security model. Basically I prevent the browser from contacting external sources for data to provide some confidence that pgp.help is not stealing your data. See here: https://github.com/Gaff/pgp.help/blob/master/README.md

What I could do is provide a gateway hosted on an alternative domain (lookup.pgp.help?) that searches the keyserver and then links to pgp.help itself. How does that sound? Do you think there's much demand for it?

**Comment by Gaff** [comment]
Incidentally you could easily do this in your demo. If you pass pgp.help a URL encoded PGP key (yes, it's going to be ugly, I know) it will open it up, like so:

https://pgp.help/#/permalink?pgp=-----BEGIN%20PGP%20PUBLIC%20KEY%20BLOCK-----%0D%0AVersion:%20OpenPGP.js%20v1.2.0%0D%0AComment:%20https:%252F%252Fpgp.help%0D%0A%0D%0AxsBNBFW7TH8BCADccz73OFQprAsBLNTFNZFTPzDUbmwKn5BMFFK7rYf7v8Gj%0APyYQrl9DupBTiP6ISyTIvn%252FpT0%252F%2BG1yTYzliej4UZP7LOUz%2Bpg59%252FX2JP7Ko%0A3UzH9qoO3FYXl85ok%252FdaSNRt0VrKSoGcMuoLw7CT48hHZdIXSwoPFP%252F%252Fn8Qo%0A3u1J3LghZQLPdnZfWHPA6ZKLvcgQaByCABsRrH7L75%2BQw49Wb3VeBiE5u26E%0Aj3NXUc1GskMvFHp8pUnfzFxF4sCzk%252Fo%2BzqJW8NtIje48beufH4eMBF2NK6nF%0A1Et8ESCM7jE10rpWm%2Bnsl8lMooQEbUXoMp2z2s2zuYmaiV%2BONaa3UT6fABEB%0AAAHNGVBncCBIZWxwIDxoZWxsb0BwZ3AuaGVscD7CwHIEEAEIACYFAlW7TIAG%0ACwkIBwMCCRAj%252FZ8%2BmwZ1aQQVCAIKAxYCAQIbAwIeAQAApGkIAJCtB3PD5aka%0ArGPzePxmqc37cpOGx%252FArO8M7ouXDkc75xt3MOMvAFB4y8lytwteXbLG50Kl0%0A1KHp1NkUEJM0eR8SxGaPipEgN0PRoEDhN8VgR3m4Lq5RlTMFq1yXQgjPGndB%0AsP%2BKIDSfBEPZOlMW9VgdzThjqj8WqVxvaoRPbazLpS%2BWYrGTx4WjcsoS53ou%0Ab7Fd6rkOdZcbgmUooDHRiNSNJq%2BRCwZnffxLlJQp3r3U0Ll4Mrsb%252FpxcOjde%0A7Cnc1SildK3m5iIuteGSIl8qXXTidcw5vV9w1xDLu7mPztaXlM72KaVkuhJN%0A%252FmSaCFTAAgECmvgP88ByG0uDu4SpeFrOwE0EVbtMfwEIAM%252F%2BtJfjT8ER4qe0%0AVJJPCqAcUffyXyABnN4NymDxz97ol9xwi2boTb2oDtTkAXmTU5pKKOjZFtV1%0AFizpVemVoGWBnmEZBaOUMZy2qFEIHrPh0OWaiuCSr%2Bm%252FVjvOWota%252F%252FbJZg1H%0A%252Fo9JaMXSefE%2BlWak%252FBZagMAX%252FEOWUfzYfNSfHViua5HxKA5PoQ7Blcxt7T1f%0A5427XhoSpZzdbi9XjlYZmFlQ08MYG18wTVa6g8MJ7qr9TIVZPRnSrtE15iP1%0A8py3tXn97PToLd78ZkTfnlKZwrMxuFHcNCHMpVbEXD6zVWATeMMNRo5an3kg%0AdE9%2B9odr2zZWdJgnN1PDwbGKeEEAEQEAAcLAXwQYAQgAEwUCVbtMgQkQI%252F2f%0APpsGdWkCGwwAAL2qCACSkHd3SDv1XTJJcwsazkXr%2BNMJaNSN7qQFPMboDS0Z%0A3pX27Rn1ev1UHTqFKBYgogxyeUOnbeXE%2BVAFYuoeNCbFYY1TFhvGVWRax%252Frf%0APBuVQ4d1%2Bg87nxSL3JFwvSGzTjPkJiU%2BrGOIkOqYK0JA%252FT8%2BZqrXTQoH2d7i%0Ar1vldA2CakQ%2BMf%2BBjHjG06doQlrbuGBYXLWJbATpcKmK%2B%2BkWaGE01h5rFbx8%0AJmS3SZME1N2bdm99TJVzbWbHqcJge%252F1lfEY1PecjweX2McXQEVGmZLPdN6dF%0AHLrZ5SS%252FqnXSXE79odO4Cd%252Fgx1nJrovmut1vZfxh3yyLOnh9%2BBZX%252FNeU9FWu%0A%0D%0A%3DMMEa%0D%0A-----END%20PGP%20PUBLIC%20KEY%20BLOCK-----%0D%0A%0D%0A

**Comment by diafygi** [comment]
No worries, you're more than welcome to set the keyserver as your own domain in the publickey.js library when you initialize it.
