### ISSUE TITLE
Fonts not loaded (404)

### ISSUE THREAD

**Issue by rugk** [Gaff/pgp.help#30]
Some fonts at `https://pgp.help/fonts/glyphicons-halflings` cannot be loaded (404 error), which causes some broken icons.

They are just [not included in your repo](https://github.com/Gaff/pgp.help/tree/gh-pages/fonts).

**Comment by Gaff** [comment]
Ugh - good spot. Shouldn't bee too tricky to pull them in I guess. Might not get a chance to fix until the weekend though.

**Comment by Gaff** [comment]
Fixed in pull 35 I hope.

**Comment by rugk** [comment]
You can just link to it (`#35`): #35
