### ISSUE TITLE
Unexpacted behaviour when adding key

### ISSUE THREAD

**Issue by rugk** [Gaff/pgp.help#41]
I have a public key which I'd like to add, but pgp.help does really behave strange. It is a key with multiple mail addresses assigned to the same public key.

When using the original key it appears 4 times in the "Public keys" section.

When I import it into Mailvelope and export it there to paste it into pgp.help it is even stranger: pgp.help does not accept my key and displays a red border...

I'll mail you the keys.

**Comment by Gaff** [comment]
Yeah fails for me too. Likely to be an upstream issue with openpgp.js. Really should encapsulate it into a minimal example an send it to them.

**Comment by rugk** [comment]
Yes, please do so, if you can. I see nothing special about the specific PGP-key I sent you, so I do not know what has to be there for a minimal example.
